services:
  store-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store-api
    ports:
      - "4000:3000"
    volumes:
      - .:/app

  store-db:
    image: postgres:17.5
    container_name: store-db
    environment:
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: store_password
      POSTGRES_DB: store_db
    ports:
      - "4001:5432"
    volumes:
      - store_db_data:/var/lib/postgresql/data

volumes:
  store_db_data:
    driver: local